### ISSUE TITLE
TT Positive font - any chance to open-source it?

### ISSUE THREAD

**Issue by orchestr7** [koobiq/design-tokens#44]
Hey guys, 

I am looking for "TT Positive" font, but is not able to find it anywhere. 
Is there any chance to download it somewhere or some link to CDN with it?

**Comment by akuleshov7** [comment]
You can also share it internally.

**Comment by pimenovoleg** [comment]
This font will not be open source, because it has a paid license. For OSS, we recommend using the `Inter` font

In the coming month, we have plans to do this more explicitly and describe how

**Comment by orchestr7** [comment]
> This font will not be open source, because it has a paid license. For OSS, we recommend using the `Inter` font
> 
> In the coming month, we have plans to do this more explicitly and describe how

Got it, thank you, feel free to close this issue

**Comment by orchestr7** [comment]
Thanks for the suggestion about `Inter`, good one
